### ISSUE TITLE
BB.promisify is not a function

### ISSUE THREAD

**Issue by ghost** [zkat/cacache#127]
```
const chownr = BB.promisify(require('chownr'))
                  ^
TypeError: BB.promisify is not a function
 at Object.<anonymous> (/Users/Ogntng/Workspaces/ganteng/node_modules/cacache/lib/util/fix-owner.js:5:19)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
```

**Comment by zkat** [comment]
@ogntng do you have a more complete repro? This is very strange, unless something very weird is going on with your bluebird.

**Comment by ghost** [comment]
sorry missplace put issue + less descriptive repro 🙇 the error is => i try to implement https://github.com/airbnb/hypernova with node (v 8.11.1)

problem solve with downgrade node version under 8
